#### Notebook 3 - Merge and Clean Dataset

<small>
Notebook ini bertujuan untuk menggabungkan seluruh dataset yang telah diproses menjadi satu dataset utama.

Tahapan yang dilakukan meliputi:

- Load processed dataset
- Merge dataset
- Membersihkan teks
- Menghapus duplicate
- Menyimpan dataset final</small>

In [100]:
import pandas as pd
import matplotlib.pyplot as plt
import re

In [101]:
df1 = pd.read_csv("../data/processed/train_clean.csv")
df2 = pd.read_csv("../data/processed/test_clean.csv")
df3 = pd.read_csv("../data/processed/finance_clean.csv")
df4 = pd.read_csv("../data/processed/transaction_clean.csv")

df5 = pd.read_csv("../data/processed/transport_clean.csv")
df6 = pd.read_csv("../data/processed/transfer_clean.csv")
df7 = pd.read_csv("../data/processed/topup_clean.csv")
df8 = pd.read_csv("../data/processed/donation_clean.csv")
df9 = pd.read_csv("../data/processed/fees_clean.csv")

df10 = pd.read_csv("../data/processed/manual_clean.csv")

In [102]:
merged = pd.concat(
    [
        df1,
        df2,
        df3,
        df4,
        df5,
        df6,
        df7,
        df8,
        df9,
        df10
    ],
    ignore_index=True
)

In [103]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

merged["clean_text"] = merged["text"].apply(clean_text)

In [104]:
print(merged.columns)

Index(['text', 'label', 'clean_text'], dtype='object')

In [105]:
merged.head()

,text,label,clean_text
0,Pembayaran restoran sebesar Rp 48698 via UPI R...,food,pembayaran restoran sebesar rp 48698 via upi r...
1,Pembelian tiket kereta sebesar Rp 9244 via UPI...,travel,pembelian tiket kereta sebesar rp 9244 via upi...
2,Pembelian paket makan siang sebesar Rp 5797 vi...,food,pembelian paket makan siang sebesar rp 5797 vi...
3,SIP reksa dana sebesar Rp 2052 via UPI Ref 198246,investment,sip reksa dana sebesar rp 2052 via upi ref 198246
4,Pembelian tiket kereta sebesar Rp 33218 via UP...,travel,pembelian tiket kereta sebesar rp 33218 via up...

In [106]:
merged = merged.drop_duplicates(
    subset=[
        "clean_text",
        "label"
    ]
)

In [107]:
print(merged.shape)

(3906, 3)

In [108]:
merged.head()

,text,label,clean_text
0,Pembayaran restoran sebesar Rp 48698 via UPI R...,food,pembayaran restoran sebesar rp 48698 via upi r...
1,Pembelian tiket kereta sebesar Rp 9244 via UPI...,travel,pembelian tiket kereta sebesar rp 9244 via upi...
2,Pembelian paket makan siang sebesar Rp 5797 vi...,food,pembelian paket makan siang sebesar rp 5797 vi...
3,SIP reksa dana sebesar Rp 2052 via UPI Ref 198246,investment,sip reksa dana sebesar rp 2052 via upi ref 198246
4,Pembelian tiket kereta sebesar Rp 33218 via UP...,travel,pembelian tiket kereta sebesar rp 33218 via up...

In [109]:
merged["label"].value_counts()

label
education        515
healthcare       451
transfer         353
shopping         321
bills            321
entertainment    246
food             224
topup            224
transport        219
donation         219
income           196
loan             183
fees             159
travel           147
investment       128
Name: count, dtype: int64

##### Text Cleaning

Membersihkan teks agar format seluruh transaksi menjadi konsisten sebelum dilakukan ekstraksi fitur menggunakan TF-IDF.

In [110]:
def clean_text(text):

    text = str(text).lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [111]:
merged["clean_text"] = merged["text"].apply(clean_text)

In [112]:
merged[
    ["text","clean_text"]
].head()

,text,clean_text
0,Pembayaran restoran sebesar Rp 48698 via UPI R...,pembayaran restoran sebesar rp 48698 via upi r...
1,Pembelian tiket kereta sebesar Rp 9244 via UPI...,pembelian tiket kereta sebesar rp 9244 via upi...
2,Pembelian paket makan siang sebesar Rp 5797 vi...,pembelian paket makan siang sebesar rp 5797 vi...
3,SIP reksa dana sebesar Rp 2052 via UPI Ref 198246,sip reksa dana sebesar rp 2052 via upi ref 198246
4,Pembelian tiket kereta sebesar Rp 33218 via UP...,pembelian tiket kereta sebesar rp 33218 via up...

In [113]:
merged.isnull().sum()

text          0
label         0
clean_text    0
dtype: int64

In [114]:
merged = merged.reset_index(drop=True)

In [115]:
print(merged.shape)

(3906, 3)

In [116]:
print(merged["label"].value_counts())

label
education        515
healthcare       451
transfer         353
shopping         321
bills            321
entertainment    246
food             224
topup            224
transport        219
donation         219
income           196
loan             183
fees             159
travel           147
investment       128
Name: count, dtype: int64

In [117]:
print(sorted(merged["label"].unique()))

['bills', 'donation', 'education', 'entertainment', 'fees', 'food', 'healthcare', 'income', 'investment', 'loan', 'shopping', 'topup', 'transfer', 'transport', 'travel']

In [118]:
for label in sorted(merged["label"].unique()):

    print("="*60)

    print(label)

    print(
        merged[
            merged["label"]==label
        ]["text"].sample(
            min(5,len(merged[merged["label"]==label])),
            random_state=42
        ).tolist()
    )

============================================================
bills
['Bayar tagihan e-wallet', 'Bayar tagihan smart home', 'Bayar tagihan publication', 'Arisan', 'Bayar tagihan air']
============================================================
donation
['Bayar infak kebaikan', 'Donasi untuk pengungsi', 'Infak di bulan Ramadan', 'Sumbangan pendidikan', 'Donasi bencana gempa']
============================================================
education
['Bayar kursus industrial design', 'Sertifikasi SAP', 'TOEFL prediction test', 'Beli buku public relations', 'Sertifikasi Microsoft']
============================================================
entertainment
['Steam Wallet Rp200000', 'Netflix', 'Langganan Sundance Now', 'Top up game Valorant points', 'Top up game Perfect World Mobile']
============================================================
fees
['Biaya admin pembayaran internet', 'Potongan admin maintenance fee', 'Potongan admin annual fee', 'Potongan admin tebus', 'Biaya admin rekening']
============================================================
food
['Pembayaran restoran sebesar Rp 7285 via UPI Ref 260265', 'Pembayaran restoran sebesar Rp 19774 via UPI Ref 797118', 'Tagihan kafe sebesar Rp 35424 via UPI Ref 679104', 'Pembelian di toko kelontong sebesar Rp 39663 via UPI Ref 174357', 'Bakso Pak Kumis jam 7 malam']
============================================================
healthcare
['Beli obat difteri', 'Medical check up tahunan Rp1200000', 'Tes gula darah puasa', 'Konsultasi KB', 'Beli suplemen kalsium']
============================================================
income
['Pendapatan dari pilot', 'Pendapatan dari 3D', 'Keuntungan Penjualan', 'Pendapatan dari dropshipping', 'Pendapatan dari lawyer']
============================================================
investment
['Deposito berjangka sebesar Rp 25084 via UPI Ref 504832', 'Pembelian kripto sebesar Rp 19587 via UPI Ref 717113', 'SIP reksa dana sebesar Rp 13655 via UPI Ref 973349', 'Investasi premi asuransi sebesar Rp 32225 via UPI Ref 210665', 'Pembelian kripto sebesar Rp 13554 via UPI Ref 246499']
============================================================
loan
['Pembayaran cicilan peralatan elektronik sebesar Rp 3429 via UPI Ref 196781', 'Cicilan mobil sebesar Rp 48985 via UPI Ref 677124', 'Bayar pinjaman BCA', 'Pembayaran cicilan peralatan elektronik sebesar Rp 2873 via UPI Ref 295652', 'Angsuran mobil tinggal 3 kali']
============================================================
shopping
['Laptop ASUS VivoBook idaman', 'Tagihan toko mode sebesar Rp 22575 via UPI Ref 978775', 'Jam tangan Casio klasik', 'Belanja di mal sebesar Rp 47505 via UPI Ref 698782', 'Belanja di mal sebesar Rp 11785 via UPI Ref 146156']
============================================================
topup
['Isi saldo LinkAja pakai internet banking', 'Top Up LinkAja buat bayar app', 'Top Up DANA buat bayar gula', 'Top Up LinkAja buat bayar dompet', 'Top Up GoPay Rp150000']
============================================================
transfer
['Transfer ke rekening neobank', 'Pindah dana ke rekening distributor', 'Transfer ke rekening perkumpulan', 'Transfer ke rekening Marshall', 'Kirim uang ke supervisor']
============================================================
transport
['Naik kopaja', 'Bayar parkir minimarket', 'Bayar parkir Mall', 'GrabBike', 'Naik taksi Blue Bird']
============================================================
travel
['Pemesanan hotel sebesar Rp 1277 via UPI Ref 144206', 'Pembelian tiket kereta sebesar Rp 11491 via UPI Ref 678805', 'Pembayaran pom bensin sebesar Rp 49711 via UPI Ref 118349', 'Pemesanan bus sebesar Rp 7664 via UPI Ref 212235', 'Pemesanan bus sebesar Rp 46872 via UPI Ref 645534']

In [119]:
merged.to_csv(
    "../data/final/merged_dataset.csv",
    index=False
)

In [120]:
merged.head()

,text,label,clean_text
0,Pembayaran restoran sebesar Rp 48698 via UPI R...,food,pembayaran restoran sebesar rp 48698 via upi r...
1,Pembelian tiket kereta sebesar Rp 9244 via UPI...,travel,pembelian tiket kereta sebesar rp 9244 via upi...
2,Pembelian paket makan siang sebesar Rp 5797 vi...,food,pembelian paket makan siang sebesar rp 5797 vi...
3,SIP reksa dana sebesar Rp 2052 via UPI Ref 198246,investment,sip reksa dana sebesar rp 2052 via upi ref 198246
4,Pembelian tiket kereta sebesar Rp 33218 via UP...,travel,pembelian tiket kereta sebesar rp 33218 via up...

In [121]:
merged[merged["label"]=="food"].sample(30, random_state=42)["text"].tolist()

['Pembayaran restoran sebesar Rp 7285 via UPI Ref 260265',
 'Pembayaran restoran sebesar Rp 19774 via UPI Ref 797118',
 'Tagihan kafe sebesar Rp 35424 via UPI Ref 679104',
 'Pembelian di toko kelontong sebesar Rp 39663 via UPI Ref 174357',
 'Bakso Pak Kumis jam 7 malam',
 'Tagihan kafe sebesar Rp 26695 via UPI Ref 409890',
 'Pembelian di toko kelontong sebesar Rp 32384 via UPI Ref 221761',
 'Pembelian di toko kelontong sebesar Rp 47343 via UPI Ref 901282',
 'Bakmi GM',
 "McDonald's",
 'Tagihan kafe sebesar Rp 34076 via UPI Ref 479353',
 'Tagihan kafe sebesar Rp 14825 via UPI Ref 167136',
 'Bakso beranak isi telur',
 'Pesanan Swiggy sebesar Rp 45386 via UPI Ref 256294',
 'Pesanan Swiggy sebesar Rp 17218 via UPI Ref 287241',
 'Pembayaran restoran sebesar Rp 22854 via UPI Ref 658623',
 'Makan bakso',
 'Pembayaran toko roti sebesar Rp 30474 via UPI Ref 189365',
 'Bakso beranak kesukaan',
 'Transaksi di restoran pizza sebesar Rp 30481 via UPI Ref 266309',
 'Tagihan kafe sebesar Rp 8780 via UPI Ref 845609',
 'Pesanan Swiggy sebesar Rp 4072 via UPI Ref 522179',
 'Tagihan kafe sebesar Rp 43158 via UPI Ref 918691',
 'Pembayaran toko roti sebesar Rp 27298 via UPI Ref 217455',
 'Pembayaran restoran sebesar Rp 25415 via UPI Ref 261472',
 'Tagihan kafe sebesar Rp 25774 via UPI Ref 485776',
 'Richeese Factory',
 'Makan malam di hotel sebesar Rp 46045 via UPI Ref 416869',
 'Makan malam di hotel sebesar Rp 11002 via UPI Ref 827712',
 'Pembelian di toko kelontong sebesar Rp 43241 via UPI Ref 641569']

In [122]:
merged[merged["label"]=="food"].sample(100, random_state=42)["text"].tolist()

['Pembayaran restoran sebesar Rp 7285 via UPI Ref 260265',
 'Pembayaran restoran sebesar Rp 19774 via UPI Ref 797118',
 'Tagihan kafe sebesar Rp 35424 via UPI Ref 679104',
 'Pembelian di toko kelontong sebesar Rp 39663 via UPI Ref 174357',
 'Bakso Pak Kumis jam 7 malam',
 'Tagihan kafe sebesar Rp 26695 via UPI Ref 409890',
 'Pembelian di toko kelontong sebesar Rp 32384 via UPI Ref 221761',
 'Pembelian di toko kelontong sebesar Rp 47343 via UPI Ref 901282',
 'Bakmi GM',
 "McDonald's",
 'Tagihan kafe sebesar Rp 34076 via UPI Ref 479353',
 'Tagihan kafe sebesar Rp 14825 via UPI Ref 167136',
 'Bakso beranak isi telur',
 'Pesanan Swiggy sebesar Rp 45386 via UPI Ref 256294',
 'Pesanan Swiggy sebesar Rp 17218 via UPI Ref 287241',
 'Pembayaran restoran sebesar Rp 22854 via UPI Ref 658623',
 'Makan bakso',
 'Pembayaran toko roti sebesar Rp 30474 via UPI Ref 189365',
 'Bakso beranak kesukaan',
 'Transaksi di restoran pizza sebesar Rp 30481 via UPI Ref 266309',
 'Tagihan kafe sebesar Rp 8780 via UPI Ref 845609',
 'Pesanan Swiggy sebesar Rp 4072 via UPI Ref 522179',
 'Tagihan kafe sebesar Rp 43158 via UPI Ref 918691',
 'Pembayaran toko roti sebesar Rp 27298 via UPI Ref 217455',
 'Pembayaran restoran sebesar Rp 25415 via UPI Ref 261472',
 'Tagihan kafe sebesar Rp 25774 via UPI Ref 485776',
 'Richeese Factory',
 'Makan malam di hotel sebesar Rp 46045 via UPI Ref 416869',
 'Makan malam di hotel sebesar Rp 11002 via UPI Ref 827712',
 'Pembelian di toko kelontong sebesar Rp 43241 via UPI Ref 641569',
 'Bakso Pak Kumis porsi jumbo',
 'Tagihan kafe sebesar Rp 35328 via UPI Ref 242254',
 'Tagihan kafe sebesar Rp 4517 via UPI Ref 132938',
 'HokBen',
 'Warung Nasi',
 'Pesanan Swiggy sebesar Rp 45615 via UPI Ref 232937',
 'Cemilan',
 'Pengiriman makanan Zomato sebesar Rp 12935 via UPI Ref 967463',
 'Pembayaran restoran sebesar Rp 15799 via UPI Ref 169187',
 'Fore Coffee',
 'Pesanan Swiggy sebesar Rp 49254 via UPI Ref 741597',
 'Bakso Malang pake mie kuning',
 'Es Teh Indonesia',
 'Pembayaran restoran sebesar Rp 1890 via UPI Ref 912965',
 'GrabFood',
 'Transaksi di restoran pizza sebesar Rp 13726 via UPI Ref 352067',
 'Transaksi di restoran pizza sebesar Rp 1012 via UPI Ref 377304',
 'Makan malam di hotel sebesar Rp 38122 via UPI Ref 323781',
 'Pembayaran restoran sebesar Rp 27189 via UPI Ref 212149',
 'Pembelian di toko kelontong sebesar Rp 17214 via UPI Ref 448206',
 'Pembelian di toko kelontong sebesar Rp 21974 via UPI Ref 433774',
 'Kopi',
 'Pesanan Swiggy sebesar Rp 44931 via UPI Ref 513892',
 'Pembelian paket makan siang sebesar Rp 11575 via UPI Ref 817686',
 'Transaksi di restoran pizza sebesar Rp 38890 via UPI Ref 691807',
 'Pembayaran toko roti sebesar Rp 8673 via UPI Ref 768061',
 'Makan malam di hotel sebesar Rp 34807 via UPI Ref 168466',
 'Mixue',
 "Domino's Pizza",
 'Pembelian paket makan siang sebesar Rp 49309 via UPI Ref 379786',
 'Tagihan kafe sebesar Rp 26213 via UPI Ref 444207',
 'Pembayaran restoran sebesar Rp 38384 via UPI Ref 599948',
 'Chatime',
 'Bakso Pak Slamet rame',
 'Tagihan kafe sebesar Rp 48400 via UPI Ref 834285',
 'Bakso urat kenyal',
 'Pembayaran restoran sebesar Rp 43436 via UPI Ref 338968',
 'Tagihan kafe sebesar Rp 17601 via UPI Ref 675898',
 'Makan malam di hotel sebesar Rp 14279 via UPI Ref 934375',
 'Pembelian di toko kelontong sebesar Rp 15751 via UPI Ref 314580',
 'Pembelian di toko kelontong sebesar Rp 39311 via UPI Ref 662971',
 'Pengiriman makanan Zomato sebesar Rp 49524 via UPI Ref 336574',
 'Pembayaran toko roti sebesar Rp 34511 via UPI Ref 663679',
 'Solaria',
 'Makan malam di hotel sebesar Rp 26824 via UPI Ref 911235',
 'Transaksi di restoran pizza sebesar Rp 37887 via UPI Ref 299312',
 'Pembayaran toko roti sebesar Rp 20253 via UPI Ref 351083',
 'Makan malam di hotel sebesar Rp 27260 via UPI Ref 760356',
 'Transaksi di restoran pizza sebesar Rp 2637 via UPI Ref 593554',
 'Pengiriman makanan Zomato sebesar Rp 15733 via UPI Ref 232352',
 'Kopi Kenangan',
 'Tagihan kafe sebesar Rp 45214 via UPI Ref 495618',
 'Pembayaran restoran sebesar Rp 10863 via UPI Ref 601656',
 'Pesanan Swiggy sebesar Rp 13717 via UPI Ref 755900',
 'Beli sate ayam',
 'Bakso Pak Darto favorit',
 'Pembayaran toko roti sebesar Rp 6131 via UPI Ref 470399',
 'Tagihan kafe sebesar Rp 13165 via UPI Ref 979995',
 'Transaksi di restoran pizza sebesar Rp 47839 via UPI Ref 332656',
 'Pembelian paket makan siang sebesar Rp 26475 via UPI Ref 322675',
 'Pengiriman makanan Zomato sebesar Rp 45755 via UPI Ref 519517',
 'Pembelian di toko kelontong sebesar Rp 23997 via UPI Ref 934794',
 'Transaksi di restoran pizza sebesar Rp 33462 via UPI Ref 677022',
 'Beli nasi goreng di abang pinggir jalan',
 'Transaksi di restoran pizza sebesar Rp 2377 via UPI Ref 858498',
 'Pembayaran restoran sebesar Rp 48698 via UPI Ref 388389',
 'Pembelian paket makan siang sebesar Rp 13131 via UPI Ref 850800',
 'Pesanan Swiggy sebesar Rp 10735 via UPI Ref 252895',
 'Tagihan kafe sebesar Rp 47290 via UPI Ref 526170',
 'Makan bakso sama teman']

In [123]:
merged["label"].value_counts()

label
education        515
healthcare       451
transfer         353
shopping         321
bills            321
entertainment    246
food             224
topup            224
transport        219
donation         219
income           196
loan             183
fees             159
travel           147
investment       128
Name: count, dtype: int64

#### Kesimpulan
<small>
Seluruh dataset berhasil digabungkan menjadi satu dataset utama.

Dataset akhir telah melalui proses:

- Penggabungan dataset
- Pembersihan teks
- Penghapusan data duplikat
- Pemeriksaan missing value

Dataset yang dihasilkan akan digunakan pada tahap ekstraksi fitur dan pelatihan model Machine Learning.</small>